server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mariadb://localhost:3306/book_service
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin123
  flyway:
    url: jdbc:mariadb://localhost:3306/
    schemas: book_service
    user: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  jackson:
    default-property-inclusion: NON_NULL
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka