server:
  port: 8888
spring:
  application:
    name: greeting-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/neogedom/config-server
          default-label: main
